spring.application.name=projectforSpringR2DBC

## H2 記憶體資料庫:
#spring.r2dbc.url=r2dbc:h2:mem://localhost:3306/testdb
## H2 帳號預設為sa, 密碼可為空或自訂
#spring.r2dbc.username=sa
#spring.r2dbc.password=password




# MySQL -> 會去使用MariaDB
spring.r2dbc.url=r2dbc:mariadb://localhost:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
spring.r2dbc.username=root
spring.r2dbc.password=Kk11032035


# AWS:

#spring.r2dbc.url=r2dbc:mariadb://database-1.....
#spring.r2dbc.username=root
#spring.r2dbc.password=12345678

spring.sql.init.mode=always